spring:
  application:
    name: jobport

  jpa:
    hibernate:
      ddl-auto: none  # ?? ?? ? create/update, ?? ??? validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # (?? ???? ??)

#  flyway:
#    enabled: true
#    locations: classpath:db/migration

#  docker:
#    compose:
#      file: ./compose-local.yaml
#      profiles: [ "dev" ]
#      start: true
#      stop: true
#      lifecycle-management: start_and_stop