spring:
  application:
    name: jobport

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto:
    show-sql:
    properties:
      hibernate:
        format_sql:
        dialect:

  ssh:
    host:
    port:
    username:
    password:
    tunnel:
      localPort:
      remoteHost:
      remotePort: